// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Min Stack
// https://leetcode.com/problems/min-stack/
// 

class MinStack {
public:
    void push(int x) {
        m_st.push(x);
        if (m_minst.empty() || x <= m_minst.top()) {
            m_minst.push(x);
        }
    }
    
    void pop() {
        if (!m_st.empty()) {
            int e = m_st.top();
            m_st.pop();
            if (e == m_minst.top()) {
                m_minst.pop();
            }
        }
    }
    
    int top() {
        return m_st.top();
    }
    
    int getMin() {
        return m_minst.top();
    }
    
private:
    stack<int> m_st, m_minst;
};

