# 
# Generated by fetch-leetcode-submission project on GitHub.
# https://github.com/gitzhou/fetch-leetcode-submission
# Contact Me: aaron67[AT]aaron67.cc
# 
# Intersection of Two Arrays
# https://leetcode.com/problems/intersection-of-two-arrays/
# 

# @param {Integer[]} nums1
# @param {Integer[]} nums2
# @return {Integer[]}
def intersection(nums1, nums2)
  return nil if nums1.nil? || nums2.nil?
  nums1 & nums2
end

