# 
# Generated by fetch-leetcode-submission project on GitHub.
# https://github.com/gitzhou/fetch-leetcode-submission
# Contact Me: aaron67[AT]aaron67.cc
# 
# Max Consecutive Ones
# https://leetcode.com/problems/max-consecutive-ones/
# 

# @param {Integer[]} nums
# @return {Integer}
def find_max_consecutive_ones(nums)
  (nums.join.split('0').max_by(&:size) || '').size
end

