# 
# Generated by fetch-leetcode-submission project on GitHub.
# https://github.com/gitzhou/fetch-leetcode-submission
# Contact Me: aaron67[AT]aaron67.cc
# 
# 198. House Robber
# https://leetcode.com/problems/house-robber/
# 

# @param {Integer[]} nums
# @return {Integer}
def rob(nums)
  return 0 if nums == nil
  sum_picked, sum_leave = 0, 0
  nums.each do |e|
    last = sum_leave
    sum_leave = [sum_picked, sum_leave].max
    sum_picked = last + e
  end
  [sum_picked, sum_leave].max
end

# 
# You are a professional robber planning to rob houses along a street. Each house has a certain amount of money stashed, the only constraint stopping you from robbing each of them is that adjacent houses have security system connected and it will automatically contact the police if two adjacent houses were broken into on the same night. Given a list of non-negative integers representing the amount of money of each house, determine the maximum amount of money you can rob tonight without alerting the police. Credits: Special thanks to @ifanchu for adding this problem and creating all test cases. Also thanks to @ts for adding additional test cases. Subscribe to see which companies asked this question Show Tags Dynamic Programming Show Similar Problems (M) Maximum Product Subarray (M) House Robber II (M) Paint House (E) Paint Fence (M) House Robber III
# 
