// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Rotate Image
// https://leetcode.com/problems/rotate-image/
// 

class Solution {
public:
    void rotate(vector<vector<int> > &matrix) {
        int n = (int)matrix.size();
        for (int i = 0; i < n / 2; ++i) {
            for (int j = i; j < n - 1 - i; ++j) {
                // (ii, jj) ==> t2
                // t1 ==> (ii, jj)
                // t2 ==> t1
                int t1 = matrix[i][j], t2;
                // (i, j) ==> (ii, jj) = (j, n - i - 1)
                for (int k = 0; k < 4; ++k) { // 每组移动4个元素
                    int ii = j, jj = n - 1 - i;
                    t2 = matrix[ii][jj];
                    matrix[ii][jj] = t1;
                    t1 = t2;
                    i = ii;
                    j = jj;
                }
            }
        }
    }
};

