// 
// Generated by FetchLeetcodeSubmission Project on GitCafe.
// Visit https://gitcafe.com/aaronzhou/FetchLeetcodeSubmission for more information.
// Contact Me: aaron67[AT]aaron67.cc
// 
// Convert Sorted Array to Binary Search Tree
// https://oj.leetcode.com/problems/convert-sorted-array-to-binary-search-tree/
// 

/**
 * Definition for binary tree
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode(int x) : val(x), left(NULL), right(NULL) {}
 * };
 */
class Solution {
public:
    TreeNode *sortedArrayToBST(vector<int> &num) {
        return build(num, 0, (int)(num.size() - 1));
    }
    
private:
    TreeNode *build(const vector<int> &v, int start, int end) {
        if (start > end) {
            return NULL;
        }
        int mid = (start + end) / 2;
        TreeNode *p = new TreeNode(v[mid]);
        p->left = build(v, start, mid - 1);
        p->right = build(v, mid + 1, end);
        return p;
    }
};

// 
// Given an array where elements are sorted in ascending order, convert it to a height balanced BST. Show Tags Tree Depth-first Search
// 
