# 
# Generated by fetch-leetcode-submission project on GitHub.
# https://github.com/gitzhou/fetch-leetcode-submission
# Contact Me: aaron67[AT]aaron67.cc
# 
# 
# https://leetcode.com/problems/intersection-of-two-arrays/
# 

# @param {Integer[]} nums1
# @param {Integer[]} nums2
# @return {Integer[]}
def intersection(nums1, nums2)
  return nil if nums1.nil? || nums2.nil?
  nums1 & nums2
end

# 
# Given two arrays, write a function to compute their intersection. Example: Given nums1 = [1, 2, 2, 1], nums2 = [2, 2], return [2]. Note: Each element in the result must be unique. The result can be in any order. Subscribe to see which companies asked this question Show Tags Binary Search Hash Table Two Pointers Sort Show Similar Problems (E) Intersection of Two Arrays II
# 
