// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Happy Number
// https://leetcode.com/problems/happy-number/
// 

class Solution {
public:
    bool isHappy(int n) {
        vector<int> sequence(1, n);
        while ((n = cal(n)) != 1) {
            if (find(sequence.begin(), sequence.end(), n) != sequence.end()) {
                return false;
            }
            sequence.push_back(n);
        }
        return true;
    }
    
private:
    int cal(int n) {
        int result = 0;
        while (n != 0) {
            result += (n % 10) * (n % 10);
            n /= 10;
        }
        return result;
    }
};

