// 
// Generated by FetchLeetcodeSubmission Project on GitCafe.
// Visit https://gitcafe.com/aaronzhou/FetchLeetcodeSubmission for more information.
// Contact Me: aaron67[AT]aaron67.cc
// 
// Find Minimum in Rotated Sorted Array
// https://oj.leetcode.com/problems/find-minimum-in-rotated-sorted-array/
// 

class Solution {
public:
    int findMin(vector<int> &num) {
        return *min_element(num.begin(), num.end());
    }
};

// 
// Suppose a sorted array is rotated at some pivot unknown to you beforehand. (i.e., 0 1 2 4 5 6 7 might become 4 5 6 7 0 1 2). Find the minimum element. You may assume no duplicate exists in the array. Show Tags Array Binary Search
// 
