// 
// Generated by FetchLeetcodeSubmission Project on GitCafe.
// Visit https://gitcafe.com/aaronzhou/FetchLeetcodeSubmission for more information.
// Contact Me: aaron67[AT]aaron67.cc
// 
// Find Minimum in Rotated Sorted Array
// https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/
// 

class Solution {
public:
    int findMin(vector<int> &num) {
        int from = 0, to = num.size() - 1;
        while (from < to) {
            if (num[from] < num[to]) {
                // num[from, to]有序 
                return num[from];
            }
            // 此时num[from, to]为两段有序 
            int mid = (from + to) / 2;
            if (num[from] <= num[mid]) {
                // [from, mid]有序 
                // 最小数一定在[mid+1, to]
                from = mid + 1;
            } else {
                // [mid+1, to]有序 
                // 最小数一定在[from, mid] 
                to = mid;
            }
        }
        return num[to];
    }
};

// 
// Suppose a sorted array is rotated at some pivot unknown to you beforehand. (i.e., 0 1 2 4 5 6 7 might become 4 5 6 7 0 1 2). Find the minimum element. You may assume no duplicate exists in the array. Show Tags Array Binary Search Show Similar Problems (H) Search in Rotated Sorted Array (H) Find Minimum in Rotated Sorted Array II
// 
