# 
# Generated by fetch-leetcode-submission project on GitHub.
# https://github.com/gitzhou/fetch-leetcode-submission
# Contact Me: aaron67[AT]aaron67.cc
# 
# Add Digits
# https://leetcode.com/problems/add-digits/
# 

# @param {Integer} num
# @return {Integer}
def add_digits(num)
  return 0 if num == 0
  num % 9 == 0 ? 9 : num % 9
end

