// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// First Bad Version
// https://leetcode.com/problems/first-bad-version/
// 

// Forward declaration of isBadVersion API.
bool isBadVersion(int version);

class Solution {
public:
    int firstBadVersion(int n) {
        return findFirstBadVersion(1, n);
    }
    
private:
    int findFirstBadVersion(long left, long right) { // [left, right]
        if (left == right) {
            return (int)left;
        }
        long mid = (left + right) / 2;
        return isBadVersion((int)mid)? findFirstBadVersion(1, mid): findFirstBadVersion(mid + 1, right);
    }
};

