// 
// Generated by FetchLeetcodeSubmission Project on GitCafe.
// Visit https://gitcafe.com/aaronzhou/FetchLeetcodeSubmission for more information.
// Contact Me: aaron67[AT]aaron67.cc
// 
// Reverse Bits
// https://leetcode.com/problems/reverse-bits/
// 

class Solution {
public:
    uint32_t reverseBits(uint32_t n) {
        uint32_t result = 0, target = 1;
        while (target != 0) {
            result = (result << 1) | ((n & target) == 0? 0: 1);
            target = target << 1;
        }
        return result;
    }
};

// 
// Reverse bits of a given 32 bits unsigned integer. For example, given input 43261596 (represented in binary as 00000010100101000001111010011100), return 964176192 (represented in binary as 00111001011110000010100101000000). Follow up: If this function is called many times, how would you optimize it? Related problem: Reverse Integer Credits: Special thanks to @ts for adding this problem and creating all test cases. Show Tags Bit Manipulation Show Similar Problems (E) Number of 1 Bits
// 
