# 
# Generated by fetch-leetcode-submission project on GitHub.
# https://github.com/gitzhou/fetch-leetcode-submission
# Contact Me: aaron67[AT]aaron67.cc
# 
# Move Zeroes
# https://leetcode.com/problems/move-zeroes/
# 

# @param {Integer[]} nums
# @return {Void} Do not return anything, modify nums in-place instead.
def move_zeroes(nums)
  j = 0
  nums.each_with_index do |v, i|
    next if v == 0
    nums[i], nums[j] = nums[j], nums[i] if i != j
    j += 1
  end
end

