# 
# Generated by fetch-leetcode-submission project on GitHub.
# https://github.com/gitzhou/fetch-leetcode-submission
# Contact Me: aaron67[AT]aaron67.cc
# 
# Reverse String
# https://leetcode.com/problems/reverse-string/
# 

# @param {String} s
# @return {String}
def reverse_string(s)
  s.reverse
end

