// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Valid Number
// https://leetcode.com/problems/valid-number/
// 

public class Solution {
    public boolean isNumber(String s) {
        return s.matches(
			"(\\s)*[\\+\\-]?(([0-9]*\\.?[0-9]+)|([0-9]+\\.?[0-9]*))([Ee][\\+\\-]?[0-9]+)?(\\s)*");
    }
}

