// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Single Number
// https://leetcode.com/problems/single-number/
// 

class Solution {
public:
    int singleNumber(int A[], int n) {
        int single = A[0];
        for (int i = 1; i < n; ++i) {
            single ^= A[i];
        }
        return single;
    }
};

