// 
// Generated by FetchLeetcodeSubmission Project on GitCafe.
// Visit https://gitcafe.com/aaronzhou/FetchLeetcodeSubmission for more information.
// Contact Me: aaron67[AT]aaron67.cc
// 
// Single Number
// https://oj.leetcode.com/problems/single-number/
// 

class Solution {
public:
    int singleNumber(int A[], int n) {
        int single = A[0];
        for (int i = 1; i < n; ++i) {
            single ^= A[i];
        }
        return single;
    }
};

// 
// Given an array of integers, every element appears twice except for one. Find that single one. Note: Your algorithm should have a linear runtime complexity. Could you implement it without using extra memory? Show Tags Hash Table Bit Manipulation
// 
