// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Remove Duplicates from Sorted Array
// https://leetcode.com/problems/remove-duplicates-from-sorted-array/
// 

class Solution {
public:
    int removeDuplicates(int A[], int n) {
        int length = 0;
        for (int i = 0; i < n; ++i) {
            ++length;
            int j = i + 1;
            while (j < n && A[j] <= A[i]) {
                ++j;
            }
            if (j == n) {
                break;
            }
            A[i + 1] = A[j];
        }
        return length;
    }
};

