// 
// Generated by FetchLeetcodeSubmission Project on GitCafe.
// Visit https://gitcafe.com/aaronzhou/FetchLeetcodeSubmission for more information.
// Contact Me: aaron67[AT]aaron67.cc
// 
// 88. Merge Sorted Array
// https://leetcode.com/problems/merge-sorted-array/
// 

class Solution {
public:
    void merge(int A[], int m, int B[], int n) {
        int i = 0, j = 0;
        while (i < m && j < n) {
            if (A[i] <= B[j]) {
                ++i;
            } else {
                insertArray(A, m++, B[j++], i++);
            }
        }
        while (j < n) {
            insertArray(A, m++, B[j++], i++);
        }
    }
    
private:
    // 在数组A的pos位置处，插入元素e
    // 0 <= pos <= m
    void insertArray(int A[], int m, int e, int pos) {
        for (int i = m - 1; i >= pos; --i) {
            A[i + 1] = A[i];
        }
        A[pos] = e;
    }
};

// 
// Given two sorted integer arrays nums1 and nums2, merge nums2 into nums1 as one sorted array. Note: You may assume that nums1 has enough space (size that is greater or equal to m + n) to hold additional elements from nums2. The number of elements initialized in nums1 and nums2 are m and n respectively. Subscribe to see which companies asked this question Show Tags Array Two Pointers Show Similar Problems (E) Merge Two Sorted Lists
// 
