# 
# Generated by FetchLeetcodeSubmission Project on GitCafe.
# Visit https://gitcafe.com/aaronzhou/FetchLeetcodeSubmission for more information.
# Contact Me: aaron67[AT]aaron67.cc
# 
# 217. Contains Duplicate
# https://leetcode.com/problems/contains-duplicate/
# 

require 'set'

# @param {Integer[]} nums
# @return {Boolean}
def contains_duplicate(nums)
  return nums.to_set.size != nums.size if nums != nil && nums.size != 0
  false
end

# 
# Given an array of integers, find if the array contains any duplicates. Your function should return true if any value appears at least twice in the array, and it should return false if every element is distinct. Subscribe to see which companies asked this question Show Tags Array Hash Table Show Similar Problems (E) Contains Duplicate II (M) Contains Duplicate III
# 
