// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Rotate Array
// https://leetcode.com/problems/rotate-array/
// 

class Solution {
public:
    void rotate(int nums[], int n, int k) {
        if (nums == NULL || n <= 0 || k <= 0) {
            return;
        }
        k %= n;
        reverse(nums, nums + n - k);
        reverse(nums + n - k, nums + n);
        reverse(nums, nums + n);
    }
};

