# 
# Generated by fetch-leetcode-submission project on GitHub.
# https://github.com/gitzhou/fetch-leetcode-submission
# Contact Me: aaron67[AT]aaron67.cc
# 
# House Robber
# https://leetcode.com/problems/house-robber/
# 

# @param {Integer[]} nums
# @return {Integer}
def rob(nums)
  return 0 if nums == nil
  sum_picked, sum_leave = 0, 0
  nums.each do |e|
    last = sum_leave
    sum_leave = [sum_picked, sum_leave].max
    sum_picked = last + e
  end
  [sum_picked, sum_leave].max
end

