// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Validate Binary Search Tree
// https://leetcode.com/problems/validate-binary-search-tree/
// 

/**
 * Definition for binary tree
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode(int x) : val(x), left(NULL), right(NULL) {}
 * };
 */
class Solution {
public:
    bool isValidBST(TreeNode *root) {
        return valid(root, INT_MIN, INT_MAX);
    }
    
private:
    bool valid(TreeNode *p, int min, int max) {
        if (p == NULL) {
            return true;
        }
        if (p->val > min && p->val < max) {
            return valid(p->left, min, p->val) && valid(p->right, p->val, max);
        }
        return false;
    }
};

