// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Reverse Words in a String
// https://leetcode.com/problems/reverse-words-in-a-string/
// 

class Solution {
public:
    void reverseWords(string &s) {
        stack<string> st;
        string::size_type from = s.find_first_not_of(" "), to = from;
        while (from != string::npos &&
               (to = s.find_first_of(" ", from)) != string::npos) {
            st.push(s.substr(from, to - from));
            from = s.find_first_not_of(" ", to);
        }
        if (from != string::npos) {
            st.push(s.substr(from));
        }
        s.clear();
        while (!st.empty()) {
            s += st.top();
            st.pop();
            if (!st.empty()) {
                s += " ";
            }
        }
    }
};

