// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// 136. Single Number
// https://leetcode.com/problems/single-number/
// 

class Solution {
public:
    int singleNumber(int A[], int n) {
        int single = A[0];
        for (int i = 1; i < n; ++i) {
            single ^= A[i];
        }
        return single;
    }
};

// 
// Given an array of integers, every element appears twice except for one. Find that single one. Note: Your algorithm should have a linear runtime complexity. Could you implement it without using extra memory? Subscribe to see which companies asked this question Show Tags Hash Table Bit Manipulation Show Similar Problems (M) Single Number II (M) Single Number III (M) Missing Number (H) Find the Duplicate Number
// 
