// 
// Generated by FetchLeetcodeSubmission Project on GitCafe.
// Visit https://gitcafe.com/aaronzhou/FetchLeetcodeSubmission for more information.
// Contact Me: aaron67[AT]aaron67.cc
// 
// Excel Sheet Column Number
// https://oj.leetcode.com/problems/excel-sheet-column-number/
// 

class Solution {
public:
    int titleToNumber(string s) {
        long long multi = 1;
        int result = 0;
        for (int i = (int)(s.length() - 1); i >= 0; --i) {
            result += (s[i] - 'A' + 1) * multi;
            multi *= TWENTY_SIX;
        }
        return result;
    }
    
private:
    static const int TWENTY_SIX = 26;
};

// 
// Related to question Excel Sheet Column Title Given a column title as appear in an Excel sheet, return its corresponding column number. For example:     A -> 1
//     B -> 2
//     C -> 3
//     ...
//     Z -> 26
//     AA -> 27
//     AB -> 28 Credits: Special thanks to @ts for adding this problem and creating all test cases. Show Tags Math
// 
