// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Excel Sheet Column Number
// https://leetcode.com/problems/excel-sheet-column-number/
// 

class Solution {
public:
    int titleToNumber(string s) {
        long long multi = 1;
        int result = 0;
        for (int i = (int)(s.length() - 1); i >= 0; --i) {
            result += (s[i] - 'A' + 1) * multi;
            multi *= TWENTY_SIX;
        }
        return result;
    }
    
private:
    static const int TWENTY_SIX = 26;
};

