# 
# Generated by fetch-leetcode-submission project on GitHub.
# https://github.com/gitzhou/fetch-leetcode-submission
# Contact Me: aaron67[AT]aaron67.cc
# 
# Excel Sheet Column Number
# https://leetcode.com/problems/excel-sheet-column-number/
# 

DIGIT_COUNT = 26

# @param {String} s
# @return {Integer}
def title_to_number(s)
  weight, result = 1, 0
  s.reverse.each_char do |c|
    result += (c.ord - 'A'.ord + 1) * weight
    weight *= DIGIT_COUNT
  end
  result
end

