# 
# Generated by fetch-leetcode-submission project on GitHub.
# https://github.com/gitzhou/fetch-leetcode-submission
# Contact Me: aaron67[AT]aaron67.cc
# 
# 344. Reverse String
# https://leetcode.com/problems/reverse-string/
# 

# @param {String} s
# @return {String}
def reverse_string(s)
  s.reverse
end

# 
# Write a function that takes a string as input and returns the string reversed. Example: Given s = "hello", return "olleh". Subscribe to see which companies asked this question Show Tags Two Pointers String Show Similar Problems (E) Reverse Vowels of a String
# 
