// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Remove Element
// https://leetcode.com/problems/remove-element/
// 

class Solution {
public:
    int removeElement(int A[], int n, int elem) {
        int length = 0;
        int i = 0;
        while (i < n) {
            if (A[i] == elem) {
                A[i] = A[--n];
            } else {
                ++i;
                ++length;
            }
        }
        return length;
    }
};

