// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Count and Say
// https://leetcode.com/problems/count-and-say/
// 

class Solution {
public:
    Solution() {
        sequence.push_back("1");
    }
    
    string countAndSay(int n) {
        if (n > sequence.size()) {
            size_t i = sequence.size();
            string s = sequence[i - 1], sread;
            while (i < n) {
                char ch = s[0];
                int count = 1;
                for (int j = 1; j < s.length(); ++j) {
                    if (s[j] == s[j - 1]) {
                        ++count;
                    } else {
                        sread = sread + intToString(count) + ch;
                        ch = s[j];
                        count = 1;
                    }
                }
                sread = sread + intToString(count) + ch;
                sequence.push_back(sread);
                s = sread;
                sread = "";
                ++i;
            }
        }
        return sequence[n - 1];
    }
    
private:
    string intToString(int i) {
        stringstream ss;
        ss << i;
        string s;
        ss >> s;
        return s;
    }
    
private:
    vector<string> sequence;
};

