// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Path Sum
// https://leetcode.com/problems/path-sum/
// 

/**
 * Definition for binary tree
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode(int x) : val(x), left(NULL), right(NULL) {}
 * };
 */
class Solution {
public:
    bool hasPathSum(TreeNode *root, int sum) {
        int currentSum = 0;
        bool match = false;
        preOrderTraversal(root, sum, currentSum, match);
        return match;
    }
    
private:
    void preOrderTraversal(TreeNode *node, int sum, int &currentSum, bool &match) {
        if (node == NULL) {
            return;
        }
        currentSum += node->val;
        if (currentSum == sum && node->left == NULL && node->right == NULL) {
            match = true;
        }
        preOrderTraversal(node->left, sum, currentSum, match);
        preOrderTraversal(node->right, sum, currentSum, match);
        currentSum -= node->val;
    }
};

