// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Merge Two Sorted Lists
// https://leetcode.com/problems/merge-two-sorted-lists/
// 

/**
 * Definition for singly-linked list.
 * struct ListNode {
 *     int val;
 *     ListNode *next;
 *     ListNode(int x) : val(x), next(NULL) {}
 * };
 */
class Solution {
public:
    ListNode *mergeTwoLists(ListNode *l1, ListNode *l2) {
        ListNode *list = NULL, *tail = NULL, *p = NULL;
        while (l1 != NULL && l2 != NULL) {
            if (l1->val <= l2->val) {
                p = l1;
                l1 = l1->next;
            } else {
                p = l2;
                l2 = l2->next;
            }
            p->next = NULL;
            if (list == NULL) {
                list = p;
            } else {
                tail->next = p;
            }
            tail = p;
        }
        if (l1 != NULL) {
            p = l1;
        }
        if (l2 != NULL) {
            p = l2;
        }
        if (list == NULL) {
            list = p;
        } else {
            tail->next = p;
        }
        return list;
    }
};

