# 
# Generated by fetch-leetcode-submission project on GitHub.
# https://github.com/gitzhou/fetch-leetcode-submission
# Contact Me: aaron67[AT]aaron67.cc
# 
# Contains Duplicate
# https://leetcode.com/problems/contains-duplicate/
# 

require 'set'

# @param {Integer[]} nums
# @return {Boolean}
def contains_duplicate(nums)
  return nums.to_set.size != nums.size if nums != nil && nums.size != 0
  false
end

