// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Pascal's Triangle
// https://leetcode.com/problems/pascals-triangle/
// 

class Solution {
public:
    vector<vector<int> > generate(int numRows) {
        vector<vector<int> > pascal;
        if (numRows >= 1) {
            vector<int> vi(1, 1);
            pascal.push_back(vi);
        }
        if (numRows >= 2) {
            vector<int> vi(2, 1);
            pascal.push_back(vi);
        }
        for (int i = 3; i <= numRows; ++i) {
            vector<int> vi(i, 1);
            for (int j = 1; j < i - 1; ++j) {
                vi[j] = pascal[i - 2][j - 1] + pascal[i - 2][j];
            }
            pascal.push_back(vi);
        }
        return pascal;
    }
};

