// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Plus One
// https://leetcode.com/problems/plus-one/
// 

class Solution {
public:
    vector<int> plusOne(vector<int> &digits) {
        vector<int> result;
        ++digits[digits.size() - 1];
        int carry = 0;
        for (long i = digits.size() - 1; i >= 0; --i) {
            result.push_back((digits[i] + carry) % 10);
            carry = (digits[i] + carry) / 10;
        }
        if(carry != 0) {
            result.push_back(carry);
        }
        reverse(result.begin(), result.end());
        return result;
    }
};

