// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Number of 1 Bits
// https://leetcode.com/problems/number-of-1-bits/
// 

class Solution {
public:
    int hammingWeight(uint32_t n) {
        int weight = 0;
        while (n != 0) {
            ++weight;
            n = n & (n - 1);
        }
        return weight;
    }
};

