// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Peeking Iterator
// https://leetcode.com/problems/peeking-iterator/
// 

// Below is the interface for Iterator, which is already defined for you.
// **DO NOT** modify the interface for Iterator.
class Iterator {
    struct Data;
	Data* data;
public:
	Iterator(const vector<int>& nums);
	Iterator(const Iterator& iter);
	virtual ~Iterator();
	// Returns the next element in the iteration.
	int next();
	// Returns true if the iteration has more elements.
	bool hasNext() const;
};


class PeekingIterator : public Iterator {
public:
	PeekingIterator(const vector<int>& nums) : Iterator(nums) {
	    // Initialize any member here.
	    // **DO NOT** save a copy of nums and manipulate it directly.
	    // You should only use the Iterator interface methods.
	    _is_peeked = false;
	    _value_peeked = INT_MIN;
	}

    // Returns the next element in the iteration without advancing the iterator.
	int peek() {
	    int value = _is_peeked? _value_peeked: Iterator::next();
	    _value_peeked = value;
	    _is_peeked = true;
        return value;
	}

	// hasNext() and next() should behave the same as in the Iterator interface.
	// Override them if needed.
	int next() {
	    int value = _is_peeked? _value_peeked: Iterator::next();
	    _is_peeked = false;
	    return value;
	}

	bool hasNext() const {
	    return _is_peeked || Iterator::hasNext();
	}
	
private:
    bool _is_peeked;
    int _value_peeked;
};

