# 
# Generated by fetch-leetcode-submission project on GitHub.
# https://github.com/gitzhou/fetch-leetcode-submission
# Contact Me: aaron67[AT]aaron67.cc
# 
# 242. Valid Anagram
# https://leetcode.com/problems/valid-anagram/
# 

# @param {String} s
# @param {String} t
# @return {Boolean}
def is_anagram(s, t)
  alphabet = Hash.new(0)
  s.each_char { |c| alphabet[c.to_sym] += 1 }
  t.each_char { |c| alphabet[c.to_sym] -= 1 }
  alphabet.each_value { |v| return false if v != 0 }
  true
end

# 
# Given two strings s and t, write a function to determine if t is an anagram of s. For example, s = "anagram", t = "nagaram", return true. s = "rat", t = "car", return false. Note: You may assume the string contains only lowercase alphabets. Follow up: What if the inputs contain unicode characters? How would you adapt your solution to such case? Subscribe to see which companies asked this question Show Tags Hash Table Sort Show Similar Problems (M) Group Anagrams (E) Palindrome Permutation
# 
