// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Unique Paths
// https://leetcode.com/problems/unique-paths/
// 

class Solution {
public:
    Solution() {
        memset(ways, 0, sizeof(ways));
        for (int i = 0; i < MAX_M_N; ++i) {
            ways[0][i] = 1;
            ways[i][0] = 1;
        }
        f(MAX_M_N - 1, MAX_M_N - 1);
    }
    
    int uniquePaths(int m, int n) {
        return ways[m - 1][n - 1];
    }
    
private:
    int f(int m, int n) {
        if (ways[m][n] == 0) {
            ways[m][n] = f(m - 1, n) + f(m, n - 1);
        }
        return ways[m][n];
    }
    
private:
    static const int MAX_M_N = 100;
    int ways[MAX_M_N][MAX_M_N];
};

