// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// 278. First Bad Version
// https://leetcode.com/problems/first-bad-version/
// 

// Forward declaration of isBadVersion API.
bool isBadVersion(int version);

class Solution {
public:
    int firstBadVersion(int n) {
        return findFirstBadVersion(1, n);
    }
    
private:
    int findFirstBadVersion(long left, long right) { // [left, right]
        if (left == right) {
            return (int)left;
        }
        long mid = (left + right) / 2;
        return isBadVersion((int)mid)? findFirstBadVersion(1, mid): findFirstBadVersion(mid + 1, right);
    }
};

// 
// You are a product manager and currently leading a team to develop a new product. Unfortunately, the latest version of your product fails the quality check. Since each version is developed based on the previous version, all the versions after a bad version are also bad. Suppose you have n versions [1, 2, ..., n] and you want to find out the first bad one, which causes all the following ones to be bad. You are given an API bool isBadVersion(version) which will return whether version is bad. Implement a function to find the first bad version. You should minimize the number of calls to the API. Credits: Special thanks to @jianchao.li.fighter for adding this problem and creating all test cases. Subscribe to see which companies asked this question Show Tags Binary Search Show Similar Problems (M) Search for a Range (M) Search Insert Position
// 
