// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// 27. Remove Element
// https://leetcode.com/problems/remove-element/
// 

class Solution {
public:
    int removeElement(int A[], int n, int elem) {
        int length = 0;
        int i = 0;
        while (i < n) {
            if (A[i] == elem) {
                A[i] = A[--n];
            } else {
                ++i;
                ++length;
            }
        }
        return length;
    }
};

// 
// Given an array and a value, remove all instances of that value in place and return the new length. Do not allocate extra space for another array, you must do this in place with constant memory. The order of elements can be changed. It doesn't matter what you leave beyond the new length. Example: Given input array nums = [3,2,2,3], val = 3 Your function should return length = 2, with the first two elements of nums being 2. Try two pointers. Did you use the property of "the order of elements can be changed"? What happens when the elements to remove are rare? Subscribe to see which companies asked this question Show Tags Array Two Pointers Show Similar Problems (E) Remove Duplicates from Sorted Array (E) Remove Linked List Elements (E) Move Zeroes
// 
