# 
# Generated by fetch-leetcode-submission project on GitHub.
# https://github.com/gitzhou/fetch-leetcode-submission
# Contact Me: aaron67[AT]aaron67.cc
# 
# Nim Game
# https://leetcode.com/problems/nim-game/
# 

# you can take how many stones each time
MAX_COUNT_ONE_TAKE = 3

# @param {Integer} n
# @return {Boolean}
def can_win_nim(n)
  return false if n % (MAX_COUNT_ONE_TAKE + 1) == 0
  true
end

