// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Nim Game
// https://leetcode.com/problems/nim-game/
// 

class Solution {
    public final static int MAX_COUNT_ONE_TAKE = 3;
    
    public boolean canWinNim(int n) {
        if (n % (MAX_COUNT_ONE_TAKE + 1) == 0) {
            return false;
        }
        return true;
    }
}

