// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Maximum Subarray
// https://leetcode.com/problems/maximum-subarray/
// 

class Solution {
public:
    int maxSubArray(int A[], int n) {
        int max = A[0], sum = 0;
        for (int i = 0; i < n; ++i) {
            if (sum <= 0) {
                sum = A[i];
            } else {
                sum += A[i];
            }
            
            if (sum > max) {
                max = sum;
            }
        }
        return max;
    }
};

