// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Minimum Path Sum
// https://leetcode.com/problems/minimum-path-sum/
// 

class Solution {
public:
    int minPathSum(vector<vector<int> > &grid) {
        if (grid.size() == 0) {
            return 0;
        }
        int iTable[] = {0, -1}, jTable[] = {-1, 0};
        for (int i = 0; i < grid.size(); ++i) {
            for (int j = 0; j < grid[i].size(); ++j) {
                if (i == 0 && j == 0) {
                    continue;
                }
                int current = grid[i][j];
                int left = INT_MAX, up = INT_MAX;
                if (i + iTable[0] >= 0 && j + jTable[0] >= 0) {
                    left = grid[i + iTable[0]][j + jTable[0]];
                }
                if (i + iTable[1] >= 0 && j + jTable[1] >= 0) {
                    up = grid[i + iTable[1]][j + jTable[1]];
                }
                grid[i][j] = current + min(left, up);
            }
        }
        return grid[grid.size() - 1][grid[grid.size() - 1].size() - 1];
    }
};

