// 
// Generated by FetchLeetcodeSubmission Project on GitCafe.
// Visit https://gitcafe.com/aaronzhou/FetchLeetcodeSubmission for more information.
// Contact Me: aaron67[AT]aaron67.cc
// 
// Gray Code
// https://leetcode.com/problems/gray-code/
// 

class Solution {
public:
    vector<int> grayCode(int n) {
        vector<int> result, gray(n, 0);
        dfs(result, gray, 0);
        return result;
    }
    
private:
    void dfs(vector<int> &result, vector<int> &gray, int i) {
        if (i == gray.size()) {
            int dec = binaryToDecimal(gray);
            result.push_back(dec / 2 ^ dec);
            return;
        }
        gray[i] = 0;
        dfs(result, gray, i + 1);
        gray[i] = 1;
        dfs(result, gray, i + 1);
    }
    
    int binaryToDecimal(const vector<int> &v) {
        int result = 0, two = 1;
        for (int i = (int)(v.size() - 1); i >= 0; --i, two *= 2) {
            result += v[i] * two;
        }
        return result;
    }
};

// 
// The gray code is a binary numeral system where two successive values differ in only one bit. Given a non-negative integer n representing the total number of bits in the code, print the sequence of gray code. A gray code sequence must begin with 0. For example, given n = 2, return [0,1,3,2]. Its gray code sequence is: 
// 00 - 0
// 01 - 1
// 11 - 3
// 10 - 2
//  Note: For a given n, a gray code sequence is not uniquely defined. For example, [0,2,3,1] is also a valid gray code sequence according to the above definition. For now, the judge is able to judge based on one instance of gray code sequence. Sorry about that. Show Tags Backtracking
// 
