// 
// Generated by FetchLeetcodeSubmission Project on GitCafe.
// Visit https://gitcafe.com/aaronzhou/FetchLeetcodeSubmission for more information.
// Contact Me: aaron67[AT]aaron67.cc
// 
// Compare Version Numbers
// https://oj.leetcode.com/problems/compare-version-numbers/
// 

class Solution {
public:
    int compareVersion(string version1, string version2) {
        return cmpVersion(version1, 0, version2, 0);
    }
    
private:
    int cmpVersion(const string &v1, string::size_type pos1, const string &v2, string::size_type pos2) {
        if (pos1 == string::npos && pos2 == string::npos) {
            return 0;
        }
        long pv1 = getPartValue(v1, pos1), pv2 = getPartValue(v2, pos2);
        if (pv1 == pv2) {
            return cmpVersion(v1, pos1, v2, pos2);
        }
        return pv1 > pv2? 1: -1;
    }
    
    long getPartValue(const string &s, string::size_type &p) {
        long value = 0;
        if (p != string::npos) {
            string::size_type pos = s.find_first_of('.', p);
            if (pos == string::npos) {
                value = stringToLong(s.substr(p));
                p = pos;
            } else {
                value = stringToLong(s.substr(p, pos - p));
                p = pos + 1;
            }
        }
        return value;
    }
    
    long stringToLong(const string &str) {
        stringstream ss(str);
        long result;
        ss >> result;
        return result;
    }
};

// 
// Compare two version numbers version1 and version1. If version1 > version2 return 1, if version1 < version2 return -1, otherwise return 0. You may assume that the version strings are non-empty and contain only digits and the . character. The . character does not represent a decimal point and is used to separate number sequences. For instance, 2.5 is not "two and a half" or "half way to version three", it is the fifth second-level revision of the second first-level revision. Here is an example of version numbers ordering: 0.1 < 1.1 < 1.2 < 13.37 Credits: Special thanks to @ts for adding this problem and creating all test cases. Show Tags String
// 
