// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Length of Last Word
// https://leetcode.com/problems/length-of-last-word/
// 

class Solution {
public:
    int lengthOfLastWord(const char *s) {
        const string ALPHABETS = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
        size_t length = 0;
        string str(s);
        if (str.length() != 0) {
            size_t to = str.find_last_of(ALPHABETS);
            if (to != string::npos) {
                size_t from = str.find_last_not_of(ALPHABETS, to);
                if (from == string::npos) {
                    from = -1;
                }
                length = to - from;
            }
        }
        return (int)length;
    }
};

