# 
# Generated by fetch-leetcode-submission project on GitHub.
# https://github.com/gitzhou/fetch-leetcode-submission
# Contact Me: aaron67[AT]aaron67.cc
# 
# Valid Anagram
# https://leetcode.com/problems/valid-anagram/
# 

# @param {String} s
# @param {String} t
# @return {Boolean}
def is_anagram(s, t)
  alphabet = Hash.new(0)
  s.each_char { |c| alphabet[c.to_sym] += 1 }
  t.each_char { |c| alphabet[c.to_sym] -= 1 }
  alphabet.each_value { |v| return false if v != 0 }
  true
end

