# 
# Generated by fetch-leetcode-submission project on GitHub.
# https://github.com/gitzhou/fetch-leetcode-submission
# Contact Me: aaron67[AT]aaron67.cc
# 
# Same Tree
# https://leetcode.com/problems/same-tree/
# 

# Definition for a binary tree node.
# class TreeNode
#     attr_accessor :val, :left, :right
#     def initialize(val)
#         @val = val
#         @left, @right = nil, nil
#     end
# end

# @param {TreeNode} p
# @param {TreeNode} q
# @return {Boolean}
def is_same_tree(p, q)
  return true if p == nil && q == nil
  return p.val == q.val &&
      is_same_tree(p.left, q.left) &&
      is_same_tree(p.right, q.right) if p != nil && q != nil
  false
end

