# 
# Generated by FetchLeetcodeSubmission Project on GitCafe.
# Visit https://gitcafe.com/aaronzhou/FetchLeetcodeSubmission for more information.
# Contact Me: aaron67[AT]aaron67.cc
# 
# 258. Add Digits
# https://leetcode.com/problems/add-digits/
# 

# @param {Integer} num
# @return {Integer}
def add_digits(num)
  return 0 if num == 0
  num % 9 == 0 ? 9 : num % 9
end

# 
# Given a non-negative integer num, repeatedly add all its digits until the result has only one digit. For example: Given num = 38, the process is like: 3 + 8 = 11, 1 + 1 = 2. Since 2 has only one digit, return it. Follow up: Could you do it without any loop/recursion in O(1) runtime? A naive implementation of the above process is trivial. Could you come up with other methods? What are all the possible results? How do they occur, periodically or randomly? You may find this Wikipedia article useful. Credits: Special thanks to @jianchao.li.fighter for adding this problem and creating all test cases. Subscribe to see which companies asked this question Show Tags Math Show Similar Problems (E) Happy Number
# 
