// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// 124. Binary Tree Maximum Path Sum
// https://leetcode.com/problems/binary-tree-maximum-path-sum/
// 

/**
 * Definition for binary tree
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode(int x) : val(x), left(NULL), right(NULL) {}
 * };
 */
class Solution {
public:
    int maxPathSum(TreeNode *root) {
        if (root == NULL) {
            return 0;
        }
        int maxPathSum = INT_MIN;
        postOrderTraversal(root, maxPathSum);
        return maxPathSum;
    }
    
private:
    void postOrderTraversal(TreeNode *node, int &maxPathSum) {
        if (node == NULL) {
            return;
        }
        postOrderTraversal(node->left, maxPathSum);
        postOrderTraversal(node->right, maxPathSum);
        
        int leftVal = (node->left == NULL? 0: node->left->val);
        int rightVal = (node->right == NULL? 0: node->right->val);
        int currentNodeVal = node->val;
        if (max(leftVal, rightVal) > 0) {
            node->val += max(leftVal, rightVal);
        }
        maxPathSum = max(maxPathSum, max(node->val, currentNodeVal + leftVal + rightVal));
    }
};

// 
// Given a binary tree, find the maximum path sum. For this problem, a path is defined as any sequence of nodes from some starting node to any node in the tree along the parent-child connections. The path does not need to go through the root. For example: Given the below binary tree, 
//        1
//       / \
//      2   3
//  Return 6. Subscribe to see which companies asked this question Show Tags Tree Depth-first Search Show Similar Problems (E) Path Sum (M) Sum Root to Leaf Numbers
// 
