// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Search a 2D Matrix
// https://leetcode.com/problems/search-a-2d-matrix/
// 

class Solution {
public:
    bool searchMatrix(vector<vector<int> > &matrix, int target) {
        if (matrix.size() == 0) {
            return false;
        }
        return find(matrix, target, 0, (int)(matrix[0].size() - 1));
    }
    
private:
    bool find(const vector<vector<int> > &matrix, int target, int row, int col) {
        if (row >= matrix.size() || col < 0) {
            return false;
        }
        if (matrix[row][col] == target) {
            return true;
        } else if (matrix[row][col] > target) {
            return find(matrix, target, row, col - 1);
        } else {
            return find(matrix, target, row + 1, col);
        }
    }
};

