// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// 179. Largest Number
// https://leetcode.com/problems/largest-number/
// 

class Solution {
public:
    string largestNumber(vector<int> &num) {
        vector<string> numstrs(num.size());
        for (int i = 0; i < num.size(); ++i) {
            numstrs[i] = to_string(num[i]);
        }
        sort(numstrs.begin(), numstrs.end(), comparator);
        if (numstrs[0] == "0") {
            return "0";
        }
        stringstream ss;
        for (int i = 0; i < numstrs.size(); ++i) {
            ss << numstrs[i];
        }
        return ss.str();
    }
    
private:
    static bool comparator(const string &lhs, const string &rhs) {
        return (lhs + rhs) > (rhs + lhs);
    }
};

// 
// Given a list of non negative integers, arrange them such that they form the largest number. For example, given [3, 30, 34, 5, 9], the largest formed number is 9534330. Note: The result may be very large, so you need to return a string instead of an integer. Credits: Special thanks to @ts for adding this problem and creating all test cases. Subscribe to see which companies asked this question Show Tags Sort
// 
